package registry

func builtinTools() []ToolDef {
	return []ToolDef{
		{
			Name:           "gh",
			Command:        "gh",
			Description:    "GitHub CLI — repos, issues, PRs, Actions, releases",
			Language:       "go",
			Category:       "cloud",
			VersionCommand: "gh --version",
			VersionPattern: `gh version (\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "gh"},
				{Type: "binary", Platforms: []string{"macos", "linux"}, URLTemplate: "https://github.com/cli/cli/releases/latest/download/gh_{{.Version}}_{{.OS}}_{{.Arch}}.tar.gz"},
			},
			Auth: AuthDef{
				InjectType:      "env",
				EnvVar:          "GH_TOKEN",
				AuthCheck:       "gh auth status",
				AuthCmd:         "gh auth login",
				AuthCmdHeadless: "gh auth login --web",
			},
		},
		{
			Name:           "gws",
			Command:        "gws",
			Description:    "Google Workspace CLI — Gmail, Drive, Calendar, Docs, Sheets",
			Language:       "rust",
			Category:       "cloud",
			VersionCommand: "gws --version",
			VersionPattern: `gws (\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "npm", Platforms: []string{"macos", "linux"}, Package: "@googleworkspace/cli", Global: true},
				{Type: "binary", Platforms: []string{"macos", "linux"}, URLTemplate: "https://github.com/googleworkspace/cli/releases/latest"},
			},
			Auth: AuthDef{
				InjectType: "file",
				EnvVar:     "GOOGLE_WORKSPACE_CLI_CREDENTIALS_FILE",
				AuthCheck:  "gws auth status",
				AuthCmd:    "gws auth login",
			},
			SkillsSource: "googleworkspace/cli",
		},
		{
			Name:           "gcloud",
			Command:        "gcloud",
			Description:    "Google Cloud CLI — Compute, Cloud Run, GKE, BigQuery, IAM",
			Language:       "python",
			Category:       "cloud",
			VersionCommand: "gcloud version",
			VersionPattern: `Google Cloud SDK (\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "google-cloud-sdk"},
			},
			Auth: AuthDef{
				InjectType:      "file",
				EnvVar:          "GOOGLE_APPLICATION_CREDENTIALS",
				AuthCheck:       "gcloud auth list --filter=status:ACTIVE --format=value(account)",
				AuthCmd:         "gcloud auth login",
				AuthCmdHeadless: "gcloud auth login --no-browser",
			},
		},
		{
			Name:           "aws",
			Command:        "aws",
			Description:    "AWS CLI — EC2, S3, Lambda, IAM, CloudFormation, everything",
			Language:       "python",
			Category:       "cloud",
			VersionCommand: "aws --version",
			VersionPattern: `aws-cli/(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "awscli"},
			},
			Auth: AuthDef{
				InjectType: "env",
				EnvVar:     "AWS_ACCESS_KEY_ID",
				AuthCheck:  "aws sts get-caller-identity",
				AuthCmd:    "aws configure",
			},
		},
		{
			Name:           "az",
			Command:        "az",
			Description:    "Azure CLI — VMs, App Service, AKS, SQL, Storage",
			Language:       "python",
			Category:       "cloud",
			VersionCommand: "az --version",
			VersionPattern: `azure-cli\s+(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "azure-cli"},
			},
			Auth: AuthDef{
				InjectType:      "env",
				EnvVar:          "ARM_CLIENT_ID",
				AuthCheck:       "az account show",
				AuthCmd:         "az login",
				AuthCmdHeadless: "az login --use-device-code",
			},
		},
		{
			Name:           "doctl",
			Command:        "doctl",
			Description:    "DigitalOcean CLI — Droplets, App Platform, databases, networking",
			Language:       "go",
			Category:       "cloud",
			VersionCommand: "doctl version",
			VersionPattern: `doctl version (\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "doctl"},
				{Type: "binary", Platforms: []string{"macos", "linux"}, URLTemplate: "https://github.com/digitalocean/doctl/releases/latest"},
			},
			Auth: AuthDef{
				InjectType: "env",
				EnvVar:     "DIGITALOCEAN_ACCESS_TOKEN",
				AuthCheck:  "doctl account get",
				AuthCmd:    "doctl auth init",
			},
			SkillsSource: "digitalocean-labs/do-app-platform-skills",
		},
		{
			Name:           "vercel",
			Command:        "vercel",
			Description:    "Vercel CLI — deploy frontend apps, manage domains, env vars",
			Language:       "node",
			Category:       "deploy",
			VersionCommand: "vercel --version",
			VersionPattern: `Vercel CLI (\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "npm", Platforms: []string{"macos", "linux"}, Package: "vercel", Global: true, Requires: "node >= 18"},
			},
			Auth: AuthDef{
				InjectType: "env",
				EnvVar:     "VERCEL_TOKEN",
				AuthCheck:  "vercel whoami",
				AuthCmd:    "vercel login",
			},
			SkillsSource: "vercel/vercel",
			SkillsSubdir: "skills",
		},
		{
			Name:           "netlify",
			Command:        "netlify",
			Description:    "Netlify CLI — deploy sites, manage forms, functions, identity",
			Language:       "node",
			Category:       "deploy",
			VersionCommand: "netlify --version",
			VersionPattern: `netlify-cli/(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "npm", Platforms: []string{"macos", "linux"}, Package: "netlify-cli", Global: true},
				{Type: "brew", Platforms: []string{"macos"}, Formula: "netlify-cli"},
			},
			Auth: AuthDef{
				InjectType: "env",
				EnvVar:     "NETLIFY_AUTH_TOKEN",
				AuthCheck:  "netlify status",
				AuthCmd:    "netlify login",
			},
		},
		{
			Name:           "fly",
			Command:        "fly",
			Description:    "Fly.io CLI — deploy apps globally, manage volumes, secrets",
			Language:       "go",
			Category:       "deploy",
			VersionCommand: "fly version",
			VersionPattern: `v(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "flyctl"},
				{Type: "curl_script", Platforms: []string{"macos", "linux"}, ScriptURL: "https://fly.io/install.sh"},
			},
			Auth: AuthDef{
				InjectType:      "env",
				EnvVar:          "FLY_ACCESS_TOKEN",
				AuthCheck:       "fly auth whoami",
				AuthCmd:         "fly auth login",
				AuthCmdHeadless: "fly auth login --interactive",
			},
		},
		{
			Name:           "railway",
			Command:        "railway",
			Description:    "Railway CLI — deploy apps, manage databases, env vars",
			Language:       "rust",
			Category:       "deploy",
			VersionCommand: "railway --version",
			VersionPattern: `railway (\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "railway"},
				{Type: "npm", Platforms: []string{"macos", "linux"}, Package: "@railway/cli", Global: true},
				{Type: "curl_script", Platforms: []string{"macos", "linux"}, ScriptURL: "https://cli.new"},
			},
			Auth: AuthDef{
				InjectType: "env",
				EnvVar:     "RAILWAY_TOKEN",
				AuthCheck:  "railway whoami",
				AuthCmd:    "railway login",
			},
		},
		{
			Name:           "wrangler",
			Command:        "wrangler",
			Description:    "Cloudflare Workers CLI — deploy Workers, manage KV, R2, D1",
			Language:       "node",
			Category:       "deploy",
			VersionCommand: "wrangler --version",
			VersionPattern: `wrangler (\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "npm", Platforms: []string{"macos", "linux"}, Package: "wrangler", Global: true, Requires: "node >= 18"},
			},
			Auth: AuthDef{
				InjectType: "env",
				EnvVar:     "CLOUDFLARE_API_TOKEN",
				AuthCheck:  "wrangler whoami",
				AuthCmd:    "wrangler login",
			},
		},
		{
			Name:           "terraform",
			Command:        "terraform",
			Description:    "Terraform — declarative infrastructure provisioning across any cloud",
			Language:       "go",
			Category:       "iac",
			VersionCommand: "terraform version",
			VersionPattern: `Terraform v(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "hashicorp/tap/terraform"},
				{Type: "binary", Platforms: []string{"macos", "linux"}, URLTemplate: "https://releases.hashicorp.com/terraform/"},
			},
			Auth: AuthDef{InjectType: "none"},
		},
		{
			Name:           "pulumi",
			Command:        "pulumi",
			Description:    "Pulumi — Infrastructure as Code using real programming languages",
			Language:       "go",
			Category:       "iac",
			VersionCommand: "pulumi version",
			VersionPattern: `v(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "pulumi"},
				{Type: "curl_script", Platforms: []string{"macos", "linux"}, ScriptURL: "https://get.pulumi.com"},
			},
			Auth: AuthDef{
				InjectType: "env",
				EnvVar:     "PULUMI_ACCESS_TOKEN",
				AuthCheck:  "pulumi whoami",
				AuthCmd:    "pulumi login",
			},
		},
		{
			Name:           "kubectl",
			Command:        "kubectl",
			Description:    "Kubernetes CLI — manage pods, services, deployments, config",
			Language:       "go",
			Category:       "k8s",
			VersionCommand: "kubectl version --client -o json",
			VersionPattern: `"gitVersion":\s*"v([^"]+)"`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "kubectl"},
				{Type: "binary", Platforms: []string{"macos", "linux"}, URLTemplate: "https://dl.k8s.io/release/stable.txt"},
			},
			Auth: AuthDef{
				InjectType: "file",
				AuthCheck:  "kubectl cluster-info",
				AuthCmd:    "kubectl config set-cluster",
			},
		},
		{
			Name:           "helm",
			Command:        "helm",
			Description:    "Helm — Kubernetes package manager for charts",
			Language:       "go",
			Category:       "k8s",
			VersionCommand: "helm version --short",
			VersionPattern: `v(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "helm"},
				{Type: "curl_script", Platforms: []string{"macos", "linux"}, ScriptURL: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"},
			},
			Auth: AuthDef{InjectType: "none"},
		},
		{
			Name:           "stripe",
			Command:        "stripe",
			Description:    "Stripe CLI — payments, subscriptions, webhook testing",
			Language:       "go",
			Category:       "payments",
			VersionCommand: "stripe --version",
			VersionPattern: `stripe (\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "stripe/stripe-cli/stripe"},
				{Type: "binary", Platforms: []string{"macos", "linux"}, URLTemplate: "https://github.com/stripe/stripe-cli/releases/latest"},
			},
			Auth: AuthDef{
				InjectType: "env",
				EnvVar:     "STRIPE_API_KEY",
				AuthCheck:  "stripe config --list",
				AuthCmd:    "stripe login",
			},
		},
		{
			Name:           "sentry-cli",
			Command:        "sentry-cli",
			Description:    "Sentry CLI — release management, source map upload",
			Language:       "rust",
			Category:       "observability",
			VersionCommand: "sentry-cli --version",
			VersionPattern: `sentry-cli (\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "getsentry/tools/sentry-cli"},
				{Type: "npm", Platforms: []string{"macos", "linux"}, Package: "@sentry/cli", Global: true},
			},
			Auth: AuthDef{
				InjectType: "env",
				EnvVar:     "SENTRY_AUTH_TOKEN",
				AuthCheck:  "sentry-cli info",
				AuthCmd:    "sentry-cli login",
			},
		},
		{
			Name:           "firebase",
			Command:        "firebase",
			Description:    "Firebase CLI — auth, Firestore, hosting, functions, emulators",
			Language:       "node",
			Category:       "backend",
			VersionCommand: "firebase --version",
			VersionPattern: `(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "npm", Platforms: []string{"macos", "linux"}, Package: "firebase-tools", Global: true},
				{Type: "curl_script", Platforms: []string{"macos", "linux"}, ScriptURL: "https://firebase.tools"},
			},
			Auth: AuthDef{
				InjectType:      "file",
				EnvVar:          "GOOGLE_APPLICATION_CREDENTIALS",
				AuthCheck:       "firebase login --list",
				AuthCmd:         "firebase login",
				AuthCmdHeadless: "firebase login --no-localhost",
			},
		},
		{
			Name:           "supabase",
			Command:        "supabase",
			Description:    "Supabase CLI — local dev, migrations, edge functions",
			Language:       "go",
			Category:       "backend",
			VersionCommand: "supabase --version",
			VersionPattern: `(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "supabase/tap/supabase"},
				{Type: "binary", Platforms: []string{"macos", "linux"}, URLTemplate: "https://github.com/supabase/cli/releases/latest"},
			},
			Auth: AuthDef{
				InjectType: "env",
				EnvVar:     "SUPABASE_ACCESS_TOKEN",
				AuthCheck:  "supabase projects list",
				AuthCmd:    "supabase login",
			},
		},
		{
			Name:           "jq",
			Command:        "jq",
			Description:    "Lightweight command-line JSON processor",
			Language:       "c",
			Category:       "utility",
			VersionCommand: "jq --version",
			VersionPattern: `jq-(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "jq"},
				{Type: "binary", Platforms: []string{"macos", "linux"}, URLTemplate: "https://github.com/jqlang/jq/releases/latest"},
			},
			Auth: AuthDef{InjectType: "none"},
		},
		{
			Name:           "docker",
			Command:        "docker",
			Description:    "Docker CLI — build, run, and manage containers and images",
			Language:       "go",
			Category:       "utility",
			VersionCommand: "docker --version",
			VersionPattern: `Docker version (\S+),`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos"}, Formula: "docker"},
				{Type: "curl_script", Platforms: []string{"linux"}, ScriptURL: "https://get.docker.com"},
			},
			Auth: AuthDef{
				InjectType: "none",
				AuthCheck:  "docker info",
			},
		},
		{
			Name:           "ngrok",
			Command:        "ngrok",
			Description:    "Expose local servers to the internet via secure tunnels",
			Language:       "go",
			Category:       "utility",
			VersionCommand: "ngrok --version",
			VersionPattern: `ngrok version (\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "ngrok/ngrok/ngrok"},
			},
			Auth: AuthDef{
				InjectType: "env",
				EnvVar:     "NGROK_AUTHTOKEN",
				AuthCheck:  "ngrok config check",
				AuthCmd:    "ngrok config add-authtoken",
			},
		},
		{
			Name:           "vault",
			Command:        "vault",
			Description:    "HashiCorp Vault — secrets management, encryption as a service",
			Language:       "go",
			Category:       "secrets",
			VersionCommand: "vault version",
			VersionPattern: `Vault v(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "hashicorp/tap/vault"},
				{Type: "binary", Platforms: []string{"macos", "linux"}, URLTemplate: "https://releases.hashicorp.com/vault/"},
			},
			Auth: AuthDef{
				InjectType: "env",
				EnvVar:     "VAULT_TOKEN",
				AuthCheck:  "vault token lookup",
				AuthCmd:    "vault login",
			},
		},

		// ── Social Media ──────────────────────────────────────────────

		{
			Name:           "x-cli",
			Command:        "x",
			Description:    "X (Twitter) CLI — post, search, read timeline, manage account",
			Language:       "rust",
			Category:       "social",
			VersionCommand: "x --version",
			VersionPattern: `x-cli (\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "x-cli"},
			},
			Auth: AuthDef{
				InjectType: "env",
				EnvVar:     "X_API_KEY",
				AuthCheck:  "x auth status",
				AuthCmd:    "x auth login",
			},
		},
		{
			Name:           "late",
			Command:        "late",
			Description:    "Late (Zernio) — post to 13+ social platforms from one CLI",
			Language:       "node",
			Category:       "social",
			VersionCommand: "late --version",
			VersionPattern: `(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "npm", Platforms: []string{"macos", "linux"}, Package: "zernio", Global: true},
			},
			Auth: AuthDef{
				InjectType: "env",
				EnvVar:     "LATE_API_KEY",
				AuthCheck:  "late auth status",
				AuthCmd:    "late auth login",
			},
			SkillsSource: "zernio-dev/zernio-cli",
			SkillsSubdir: ".",
		},
		{
			Name:           "discordo",
			Command:        "discordo",
			Description:    "Discord terminal client — browse servers, channels, send messages",
			Language:       "go",
			Category:       "social",
			VersionCommand: "discordo --version",
			VersionPattern: `(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "discordo"},
			},
			Auth: AuthDef{
				InjectType: "env",
				EnvVar:     "DISCORD_TOKEN",
				AuthCheck:  "discordo --help",
				AuthCmd:    "discordo",
			},
		},

		// ── Productivity ──────────────────────────────────────────────

		{
			Name:           "notion",
			Command:        "notion-cli",
			Description:    "Notion CLI — manage pages, databases, blocks, comments, users",
			Language:       "go",
			Category:       "productivity",
			VersionCommand: "notion-cli --version",
			VersionPattern: `(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "4ier/tap/notion-cli"},
			},
			Auth: AuthDef{
				InjectType: "env",
				EnvVar:     "NOTION_API_KEY",
				AuthCheck:  "notion-cli users list",
				AuthCmd:    "notion-cli auth login",
			},
			SkillsSource: "4ier/notion-cli",
		},
		{
			Name:           "slack",
			Command:        "slack",
			Description:    "Slack CLI — create and manage Slack apps and workflows",
			Language:       "go",
			Category:       "productivity",
			VersionCommand: "slack --version",
			VersionPattern: `(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos"}, Formula: "slack-cli"},
				{Type: "curl_script", Platforms: []string{"macos", "linux"}, ScriptURL: "https://downloads.slack-edge.com/slack-cli/install.sh"},
			},
			Auth: AuthDef{
				InjectType: "env",
				EnvVar:     "SLACK_TOKEN",
				AuthCheck:  "slack auth info",
				AuthCmd:    "slack login",
			},
		},

		// ── Media ─────────────────────────────────────────────────────

		{
			Name:           "yt-dlp",
			Command:        "yt-dlp",
			Description:    "Download video/audio from YouTube and 1000+ sites",
			Language:       "python",
			Category:       "media",
			VersionCommand: "yt-dlp --version",
			VersionPattern: `(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "yt-dlp"},
			},
			Auth: AuthDef{InjectType: "none"},
		},

		// ── Finance ───────────────────────────────────────────────────

		{
			Name:           "ticker",
			Command:        "ticker",
			Description:    "Real-time stock, crypto, and derivatives tracker in the terminal",
			Language:       "go",
			Category:       "finance",
			VersionCommand: "ticker --version",
			VersionPattern: `(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "achannarasappa/tap/ticker"},
			},
			Auth: AuthDef{InjectType: "none"},
		},

		// ── News ──────────────────────────────────────────────────────

		{
			Name:           "circumflex",
			Command:        "clx",
			Description:    "Hacker News in the terminal — browse, read, comment",
			Language:       "go",
			Category:       "news",
			VersionCommand: "clx --version",
			VersionPattern: `(\S+)`,
			InstallMethods: []InstallMethod{
				{Type: "brew", Platforms: []string{"macos", "linux"}, Formula: "circumflex"},
			},
			Auth: AuthDef{InjectType: "none"},
		},
	}
}
